### ISSUE TITLE
Investigate the cause of unsuccessful dance demo

### ISSUE THREAD

**Issue by BillWSY** [CogRob/workspace#15]
(1) Investigate the mechanism for E-stop to work. Is it a rosnode? At which level it performs emergency stop? Which programs are affected?

(2) Rule: Before doing a demo in front of public, we should always test it on ourselves.

(3) We should have a procedure to reset the system to initial status. This could be hard given many ros packages are affected in the process, but we should figure it out.

(4) Keep in mind the E-stop behavior when we design ROS program.

**Comment by BillWSY** [comment]
I looked into the log, it shows the following invocation of dancing:

3:06 - OK
3:08 - OK
3:23 - Bad [INFO] [WallTime: 1477693410.692973] Waiting for get_planning_scene
3:24 - Bad [INFO] [WallTime: 1477693461.578094] Waiting for get_planning_scene
3:31 - Hit itself, No Disco, all [ERROR] [WallTime: 1477693880.298526] Arm goal in state: 4
3:32 - OK
3:43 - OK

I think the cause it in the ROS-portal. Echo agent and dialogue brain is working as expected. We should develop more robust dancing program.

**Comment by BillWSY** [comment]
After checking with Ruffin, I learnt that we did do some test before the guest come. However, during the demo, we changed the position of the robotic arm.

Hypothesis: Unfortunately, the arm reset procedure provided by Fetch was not reliable, as it put MoveIt package in an unknown state. Eventually, it caused the dance demo fail to initiate, or the arm hit the body during dancing.

We will recreate the scene to verify this hypothesis.

**Comment by BillWSY** [comment]
(1) Upon looking into rqt_graphs, I believe the E-stop is not configured as a rosnode, but rather connect directly to MCB (motor controller board). This matches our expectation -- E-stop behavior should depend on least components.

(2) Created [Wiki Page](https://github.com/CogRob/workspace/wiki/Rules-and-Best-Practices).

(3) Filed #16 

(4) Covered by (2) and (3).

**Comment by BillWSY** [comment]
Additional information:

## Runstop
The runstop is used to stop all operation of the joints. It works by disabling the base, arm and gripper breakers. When the runstop is pressed, the drivers will not be able to communicate with the MCBs, and thus their position and other data will not update in RVIZ nor the runtime monitor.

http://docs.fetchrobotics.com/robot_hardware.html#mechanism-terminology

**Comment by ruffsl** [comment]
@BillWSY , you mentioned the runstop, so I'll link to a related note here: https://github.com/CogRob/workspace/issues/23

**Comment by zephirefaith** [comment]
I feel it would be good practice if we can eliminate the assumptions of robot being in a certain desired state for our scripts to work. @BillWSY and @ruffsl, dyu guys know if we can add a hand-shake procedure to ros_portal <-> ROS communication protocol and how?

Since we are looking to develop something with "long-term autonomy" it's crucial our system sets up protocols for the unseen, by at least logging it if not overcoming it.

**Comment by ruffsl** [comment]
@zephirefaith if the platform needs to be serviced for whatever reason, we'll still want a standard practice of configuring our runtime deps on a stock robot we get back.

**Comment by BillWSY** [comment]
The task manager in ros portal should be aware of any accidents. It should listen to run stop button, teleop, etc. messages. And it will tell the other side these information. The AI should be able to handle these events.

**Comment by zephirefaith** [comment]
@ruffsl  Oh no, yeah. That's fine, I am not talking about software or library deps. I was talking about while running some action service on the robot the assumptions we have about robot's physical and contextual state. E.g. the arm wasn't in the state needed hence the dance could not happen. So we need to create ros nodes which take this into account by either:
1. Doing a handshake with the robot to reset it to desired state
2. Write robust actions which handle any variable start state

I feel method 1 would be a better starting point, given our quest to mine corner cases and situations where the robot breaks down.

**Comment by zephirefaith** [comment]
We need to create a routine, where the task manager does a little logging first --> record all the diagnostics that fetch offers for example, before starting off an action. And then do the standard rosbag logging for monitoring the execution.

**Comment by ruffsl** [comment]
If roscore is running, then a rosmaster and a rosout logging node pare are also running, so we can log all of the ros side of the system natively, as well as add more detail to the logs adding our own: http://wiki.ros.org/roscpp/Overview/Logging

**Comment by BillWSY** [comment]
@zephirefaith Yes -- each task should have a task prep stage. And there will be dependencies and locks, etc. We can talk about the implementation of task manager more.
@ruffsl Logging sounds good.
