### ISSUE TITLE
Introduce Lint to the workspace

### ISSUE THREAD

**Issue by BillWSY** [CogRob/workspace#20]
We should use lint tools to ensure our code quality.

**Comment by ruffsl** [comment]
Could we have a wiki section to installing the lent tools and plugins you'd like us to use, or what lint sources do you suggest? I've used them in atom before, but it was tricky to get everything talking to each other, like the lint element installed in my system up to the IDE interface.

**Comment by BillWSY** [comment]
At companies, we run a tool from the command line, and it is also automatically invoked during the pre-submit check.

Probably we should get the command tool working first, before integrate with IDEs.

For C++, we can try (cpplint from Google](https://github.com/google/styleguide/tree/gh-pages/cpplint). Python has pylint or something.

**Comment by ruffsl** [comment]
I only ask that is works with Qt Creator for c++ and atom for python

**Comment by zephirefaith** [comment]
As the technology noob here, can I ask one of you to setup a wiki for this stuff? Even one that is not too detailed will be fine.
@ruffsl did you give the QT Creator ROS plugins a go? It would be great if we can setup an IDE dedicated for ROS with common settings, would also help with the more general review of code style.

**Comment by BillWSY** [comment]
cpplint intact in ec8e10a434f0e679ced99099ea7793a3f2c669aa

**Comment by BillWSY** [comment]
@ruffsl I don't think IDE is a priority. Normally you won't get too many warnings from lint. For example:

```
➜  ros_portal git:(tools) cpplint task_agent.cc 
task_agent.cc:0:  No copyright message found.  You should have a line: "Copyright [year] <Copyright Owner>"  [legal/copyright] [5]
task_agent.cc:5:  Include the directory when naming .h files  [build/include] [4]
task_agent.cc:219:  At least two spaces is best between code and comments  [whitespace/comments] [2]
task_agent.cc:220:  At least two spaces is best between code and comments  [whitespace/comments] [2]
Done processing task_agent.cc
Total errors found: 4
```

All you need to do is fixing them before submitting a PR.

**Comment by BillWSY** [comment]
I am going to close this now. Created https://github.com/CogRob/workspace/issues/30 for a better interface.

@ruffsl feel free to reopen this issue if IDE integration is very important to you. We can feed the result from cpplint to atom, etc.
