### ISSUE TITLE
Determine the best practice to fork repos

### ISSUE THREAD

**Issue by BillWSY** [CogRob/workspace#24]
We need a way to
* Save copy of a repo so that we have a copy when it goes private
* Tag interesting repos that might be helpful for all of us (e.g. for future reference)
* Not polluting our github.com/CogRob

Solutions:
(1) We can create another organization (CogRobPublic) to save the public repos.
(2) We can fork to our personal account

**Comment by zephirefaith** [comment]
* Make your own personal forks for development
  * If an org-pertinent feature has been made - repo comes under our org
* If the repo is stale (abandoned, "contributors came under a bus") only then fork it under CogRob

**Comment by zephirefaith** [comment]
see https://github.com/CogRob/workspace/wiki/Rules-and-Best-Practices

**Comment by BillWSY** [comment]
Thank you.
