### ISSUE TITLE
Create shortcut for tools

### ISSUE THREAD

**Issue by BillWSY** [CogRob/workspace#30]
It would be great if we have a central command prefix, e.g.

* ```cogrob build_all``` builds the whole workspace
* ```cogrob test_all``` runs unit test for the whole workspace
* ```cogrob sync_master``` pulls change from master to current branch
* ```cogrob lint``` runs lint check for ```cc``` and ```py```

**Comment by ruffsl** [comment]
I think this could be useful, but would argue is still a p3 priority :/

**Comment by BillWSY** [comment]
#33 Did not took too much time. Really sleepy in the afternoon so can not do more meaningful work.

**Comment by BillWSY** [comment]
cogrob build  = catkin build / blaze build :all recursively
cogrob test = blaze test :all recursively
cogrob lint = google_cpplint

When we need more we will add more :)
