### ISSUE TITLE
Investigate Alexa AVS and Custome WakeWord

### ISSUE THREAD

**Issue by zephirefaith** [CogRob/workspace#34]
https://github.com/zephirefaith/snowboy
https://github.com/alexa/alexa-avs-sample-app

Implements a Java client...try to replicate this for a python end-point which can be seamlessly integrated with our architecture.

**Comment by BillWSY** [comment]
Snowboy seems easy to use. It provides a static library (not source code, but compiled for ubuntu-64). I think we will be able to use it and integrate into our system. Plus it works offline.

It is a good thing that it supports most of the platforms, so it should be good for us.

**Comment by zephirefaith** [comment]
I agree. I really like the fact that it's very self-contained!

**Comment by BillWSY** [comment]
I will take a look to see if we can integrate it into our system fast.

**Comment by ruffsl** [comment]
I've been digging into the AVS infrastructure for Linux, it takes a bit of setup, so I'm making a dockerfile to configure the example.

**Comment by BillWSY** [comment]
Snowboy does not compile on my machine. With their own makefile I get 
```
g++ -fPIC -msse  -msse2 -I../../ -std=c++0x -Wall -Wno-sign-compare -Wno-unused-local-typedefs -Winit-self -rdynamic -DHAVE_POSIX_MEMALIGN -Iportaudio/install/include -O3    demo.cc portaudio/install/lib/libportaudio.a ../..//lib/ubuntu64/libsnowboy-detect.a   -ldl -lm -Wl,-Bstatic -Wl,-Bdynamic -lrt -lpthread portaudio/install/lib/libportaudio.a -L/usr/lib/atlas-base -lf77blas -lcblas -llapack_atlas -latlas -lasound -o demo
/tmp/ccHfbmJO.o: In function `main':
demo.cc:(.text.startup+0x118): undefined reference to `snowboy::SnowboyDetect::SnowboyDetect(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
demo.cc:(.text.startup+0x123): undefined reference to `snowboy::SnowboyDetect::SetSensitivity(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
<builtin>: recipe for target 'demo' failed
make: *** [demo] Error 1
```

**Comment by BillWSY** [comment]
https://github.com/Kitt-AI/snowboy/issues/81#issuecomment-258234586

**Comment by zephirefaith** [comment]
@ruffsl That's awesome. Having a dockerized version of initial setup will definitely be the best thing!

@BillWSY Damn, those guys are fast!

**Comment by BillWSY** [comment]
Actually, I found it out right before they reply :)

**Comment by zephirefaith** [comment]
I am closing this issue, since we know Snowboy works for our ends. I am going to open another one specifically for discussing AVS though. Thanks @BillWSY !!

**Comment by BillWSY** [comment]
https://github.com/Kitt-AI/snowboy/issues/82
