### ISSUE TITLE
Integrate gRPC into ROS build framework

### ISSUE THREAD

**Issue by BillWSY** [CogRob/workspace#9]
We will need to compile gRPC library into our ROS node using catkin.

**Comment by BillWSY** [comment]
Ask the first step, we would like to get codelab/greeter working as a ROS package, and greeter_client/greeter_server would just be ROS nodes. Initiate the node handles, but don't need to do anything using it.

**Comment by zephirefaith** [comment]
Solved with a few tweaks. I list them all here.

Install:
* [Updated Protobuf](https://github.com/google/protobuf) (installing the debian version won't work as that doesn't support proto3, what Shengye seems to be using)
* [gRPC for C++](https://github.com/grpc/grpc/blob/master/INSTALL.md) (not included in the debian)

Also had to make a symlink for ``protoc`` in ``/usr/bin`` from ``/usr/local/bin``, for some reason the CMake was picking up ``/usr/bin/protoc`` as the default library which didn't exist. Didn't know a better solution.
I am attaching here the [CMakeLists.txt](https://github.com/CogRob/workspace/files/549379/CMakeLists.txt) which made it possible.

Changes to directory: The .cc files have been moved to ``src`` folder.

**Comment by zephirefaith** [comment]
Let me know if this makes sense. Am closing the issue for now.

**Comment by BillWSY** [comment]
SGTM for now. Sounds like this environment should be set up in a Docker container. We probably should look it at this way.

**Comment by BillWSY** [comment]
Can you create some instructions in the wiki?

**Comment by BillWSY** [comment]
When you come to the office, can we talk further on this?

It seems ros is depending on libprotobuf, which is the old version we should not use.

Due to the time limit, I am going to do it quick and dirty. I am going to use Python since it only depends on the pip package, which happens to be new. I am just going to grab the correct version of protoc that Bazel built and generate the header file.

**Comment by zephirefaith** [comment]
Status update so far:
* The files can compile fine, but then the workstation ends up with two different versions of protobuf
* Removing older library is not an option since the following depend on it:
  * openni2
  * freenect
  * costmap-2d
  * turtlebot-bringup
  * astra something

Proposal so far (by @BillWSY ), to Dockerize part of the build system, be it those mentioned above, or our development.

**Comment by BillWSY** [comment]
As an alternative solution, we can also:
* Create a Catkin package called ```protobuf3```, and have ```ros_portal``` depend on it, static link it. We can do the same for gRPC. Probably we will need to roll our own FindProtobuf CMake plugin.

Ideally, we should avoid installing dependencies into the system. Then our C++ code will build and run anywhere. For Python code, we maintain a global requirements.txt file, and the user can install it to ```virtualenv``` without using root privilege.

**Comment by BillWSY** [comment]
We created google_grpc package in github.com/CogRob/cogrob_ros.
